### ISSUE TITLE
do not allow multiple clicks

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-auth#35]
Currently there is a small lag between clicking and getting the toast feedback, which might lead to multiple clicks.

<img width="1436" alt="Screenshot 2022-06-15 at 12 35 19" src="https://user-images.githubusercontent.com/1707188/173847004-20ca05bd-6658-4aba-8ed6-54018019f40d.png">

We should not allow multiple clicks and possibly throttle or limit links from the same source using some sort of CAPTCHA.

Perhaps when you click, instead of the toast, you should see a different screen that no longer includes the button.

Tagging @dialexo, @alvrba, @victorggonzalez for their awareness.

**Comment by spaenleh** [comment]
The buttons are now loading as soon as the request is sent, this should solve the issue. Also we navigate to the success screen when we receive the confirmation that the call was successful.

Closing as this looks like it is not an issue currently. Please re-open if you encounter this issue in the future.
